### ISSUE TITLE
Please checkout experimental and review removal of \let\cleardoublepage\clearpage and addition of page breaks after table of content

### ISSUE THREAD

**Issue by lyle-univ** [lyle-univ/cos301-team-lime#13]
\let\cleardoublepage\clearpage does not appear to do anything. Also there was not page break after table of content. Please review for correctness since I am new to LaTeX. If correct I will merge to wip.

**Comment by RitzDoolabh** [comment]
I was trying to figure that out as well, I'm doing some research and will update accordingly.

**Comment by lyle-univ** [comment]
It has already been fixed in experimental. I just need someone to review that it has been done correctly. If correct, I or anyone else can just merge experimental into bugfix and then bugfix into wip.
