### ISSUE TITLE
Draft 1.3 Draft definitions, acronyms and abbreviations.

### ISSUE THREAD

**Issue by Dail-Jonker** [lyle-univ/cos301-team-lime#26]

**Comment by lyle-univ** [comment]
The table contents spills over the edge of the page.

**Comment by lyle-univ** [comment]
Also, agents are not human users. They are usually programs that perform a particular function within the system. Be it genereting new metadata based on existing data. The client was vague about the use of the word agent and he can't remember in which context it was used.
