### ISSUE TITLE
Draft 3.2.7 Administrator WebUI requirements.

### ISSUE THREAD

**Issue by SiyabongaMagubane** [lyle-univ/cos301-team-lime#56]

**Comment by lyle-univ** [comment]
Please restructure the format of the requirements to conform to the rest of the document. See the navigation base user requirements for an example of what it should look like. Be sure to make use of the FuncReq macro to typeset and format the document uniformly

**Comment by lyle-univ** [comment]
Also, please mention POPI act compliance features such as the facility to delete all data related to a particular data subject(person) upon request of that person.
